"""make uq_asset_definitions_phase_order deferrable

Revision ID: a3f6d81b0c57
Revises: f2a71c9d4e83
Create Date: 2026-08-28 00:00:00

`asset_definitions` is reseeded from `app/db/seed.py` on every boot, and a seed change that
*reorders* stages (the Pillar Page merge removed a row, shifting every `sequence_order` after it)
cannot be applied row by row while this constraint is checked immediately: the upsert that moves
stage N into slot K fails whenever the row currently holding K has not been moved out yet. There is
no ordering of the upserts that avoids this in general — a reorder can contain a cycle.

DEFERRABLE INITIALLY DEFERRED moves the check to COMMIT, so the whole reseed is judged on its final
state rather than on each intermediate one. The constraint itself is unchanged: a committed
transaction still cannot leave two stages sharing a `(phase, sequence_order)`.

Hand-authored rather than autogenerated, matching every prior migration's approach. Alembic has no
direct "alter constraint deferrability" operation, so this drops and recreates it — safe because
the constraint is not referenced by any foreign key (`run_stages` and friends FK to `asset_id`, the
primary key, not to this pair).
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f6d81b0c57"
down_revision: Union[str, None] = "f2a71c9d4e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_CONSTRAINT = "uq_asset_definitions_phase_order"
_TABLE = "asset_definitions"


def upgrade() -> None:
    op.drop_constraint(_CONSTRAINT, _TABLE, type_="unique")
    op.execute(
        f"ALTER TABLE {_TABLE} ADD CONSTRAINT {_CONSTRAINT} "
        "UNIQUE (phase, sequence_order) DEFERRABLE INITIALLY DEFERRED"
    )


def downgrade() -> None:
    op.drop_constraint(_CONSTRAINT, _TABLE, type_="unique")
    op.create_unique_constraint(_CONSTRAINT, _TABLE, ["phase", "sequence_order"])
