"""add competitor_analyses and competitors

Revision ID: b8f31d2a6c94
Revises: a1c4e6f2b7d3
Create Date: 2026-08-17 00:00:00

Adds the two tables backing the CRO competitor sub-stage (see app/db/models.py's
`CompetitorAnalysis` / `Competitor` docstrings): one parent row per competitor-analysis run,
one child row per competitor. Relational rather than a `context_entries` JSON blob because the
UI renders this output as a listing the operator reviews and approves, rather than only
replaying it into a downstream prompt.

Hand-authored rather than autogenerated, matching every prior migration's approach — verified by
compiling the equivalent `CREATE TABLE` DDL through the postgresql dialect against both models
and cross-checking it matches what is written below.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8f31d2a6c94"
down_revision: Union[str, None] = "a1c4e6f2b7d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Values carry spaces/mixed case because they are quoted verbatim from the competitor prompts'
# own output contract ("Verified" / "Partially verified" / "Unverified").
_verification_confidence = postgresql.ENUM(
    "Verified", "Partially verified", "Unverified", name="verification_confidence"
)


def upgrade() -> None:
    bind = op.get_bind()
    _verification_confidence.create(bind, checkfirst=True)

    op.create_table(
        "competitor_analyses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("asset_id", sa.String(100), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("service", sa.String(300), nullable=True),
        sa.Column("niche", sa.String(300), nullable=True),
        sa.Column("location", sa.String(300), nullable=True),
        sa.Column("requested_count", sa.SmallInteger(), nullable=False, server_default=sa.text("10")),
        sa.Column("returned_count", sa.SmallInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["asset_definitions.asset_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_competitor_analyses_run_asset", "competitor_analyses", ["run_id", "asset_id"]
    )

    op.create_table(
        "competitors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("analysis_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("domain", sa.String(300), nullable=False),
        sa.Column("name", sa.String(300), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=True),
        sa.Column(
            "verification_confidence",
            postgresql.ENUM(
                "Verified",
                "Partially verified",
                "Unverified",
                name="verification_confidence",
                create_type=False,
            ),
            nullable=False,
            server_default="Unverified",
        ),
        sa.Column("offering_summary", sa.Text(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("avg_position", sa.Float(), nullable=True),
        sa.Column("intersections", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["analysis_id"], ["competitor_analyses.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("analysis_id", "domain", name="uq_competitors_analysis_domain"),
    )
    op.create_index("ix_competitors_analysis_rank", "competitors", ["analysis_id", "rank"])


def downgrade() -> None:
    op.drop_index("ix_competitors_analysis_rank", table_name="competitors")
    op.drop_table("competitors")
    op.drop_index("ix_competitor_analyses_run_asset", table_name="competitor_analyses")
    op.drop_table("competitor_analyses")

    bind = op.get_bind()
    _verification_confidence.drop(bind, checkfirst=True)
