"""add model_tier to asset_definitions

Revision ID: 4dba3dae9f0a
Revises: f9e7c36b9b56
Create Date: 2026-08-13 01:00:00

Adds `asset_definitions.model_tier`, a native Postgres ENUM (`model_tier_enum`: opus / sonnet /
haiku) recording which Claude cost tier each DAG stage's generation call should use. See
app/db/models.py's `ModelTier` docstring and app/db/SCHEMA.md's "LLM model tiers" section for the
full rationale (gated foundation stages -> opus, generation + competitor-analysis stages ->
sonnet, narrow/high-frequency work -> haiku).

This is a separate migration on top of the initial schema (f9e7c36b9b56), not an edit to it, per
the standard Alembic practice of never mutating an already-applied revision.

`server_default='sonnet'` is set on the new column (rather than leaving it server-default-less)
so this migration is safe to run against a table that already has rows, consistent with every
other native-enum column added in the initial migration (`run_status`, `stage_status`,
`field_session_status`) always carrying a server default. `asset_definitions` has no seed data
yet as of this migration (see `scripts/seed_asset_definitions.py`, applied separately/idempotently
after this migration, not baked into it), so the default's practical effect today is limited to
"what a manually-inserted row gets if it omits model_tier" — but the seed script always specifies
an explicit value per stage regardless.

Hand-authored rather than autogenerated, matching the initial migration's approach (no live
Postgres instance available in this environment to autogenerate against) — verified by compiling
the equivalent `ALTER TABLE ... ADD COLUMN` DDL through the postgresql dialect against the updated
`AssetDefinition` model and cross-checking it matches what's written below.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4dba3dae9f0a"
down_revision: Union[str, None] = "f9e7c36b9b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_model_tier_enum = postgresql.ENUM("opus", "sonnet", "haiku", name="model_tier_enum")


def upgrade() -> None:
    bind = op.get_bind()
    _model_tier_enum.create(bind, checkfirst=True)

    op.add_column(
        "asset_definitions",
        sa.Column(
            "model_tier",
            postgresql.ENUM("opus", "sonnet", "haiku", name="model_tier_enum", create_type=False),
            nullable=False,
            server_default="sonnet",
        ),
    )


def downgrade() -> None:
    op.drop_column("asset_definitions", "model_tier")

    bind = op.get_bind()
    _model_tier_enum.drop(bind, checkfirst=True)
