"""scope chat_sessions to a user

Revision ID: b6e2f04a9d18
Revises: a3f6d81b0c57
Create Date: 2026-09-16 00:00:00

`chat_sessions` had no owner column, and `app/routers/chat_sessions.py` filtered on nothing — so
`GET /chat-sessions` returned every row in the table. Any operator who signed in read, reopened,
overwrote and deleted every other operator's conversations, and a brand-new account landed in
somebody else's history instead of an empty sidebar. This adds the column those routes now filter
on.

Nullable, not NOT NULL
----------------------
There is no owner recoverable from an existing row: `state` is the frontend store's blob and
carries no identity. So the backfill has to guess, and the migration guesses exactly once —
**the oldest account by `created_at`** — which is right on the single-operator install this is
being applied to and wrong on any other.

Every read path filters `user_id = :me`, so a row the guess could not cover (no accounts exist at
all) stays NULL and is listed for nobody. That is the fail-closed direction: an orphaned chat is
still in the table and can be reassigned with one UPDATE, whereas having shown one operator's
client work to another cannot be taken back.

`ON DELETE CASCADE` matches `user_sessions` and `password_reset_tokens` — deleting an account
takes its chats with it, rather than leaving rows no query can ever return again.

Hand-authored rather than autogenerated, matching every prior migration's approach.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6e2f04a9d18"
down_revision: Union[str, None] = "a3f6d81b0c57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "chat_sessions",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_chat_sessions_user_id",
        "chat_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Backfill to the oldest account. `LIMIT 1` inside a scalar subquery rather than a join, so the
    # statement is a no-op (leaving every row NULL, and therefore invisible) when `users` is empty
    # rather than failing the migration on an install nobody has signed up to yet.
    op.execute(
        sa.text(
            "UPDATE chat_sessions "
            "SET user_id = (SELECT id FROM users ORDER BY created_at ASC LIMIT 1) "
            "WHERE user_id IS NULL"
        )
    )

    op.create_index("ix_chat_sessions_user_updated", "chat_sessions", ["user_id", "updated_at"])


def downgrade() -> None:
    op.drop_index("ix_chat_sessions_user_updated", table_name="chat_sessions")
    op.drop_constraint("fk_chat_sessions_user_id", "chat_sessions", type_="foreignkey")
    op.drop_column("chat_sessions", "user_id")
