"""add chat_sessions

Revision ID: a1c4e6f2b7d3
Revises: 4dba3dae9f0a
Create Date: 2026-08-16 00:00:00

Adds `chat_sessions`, an autosave of the chat-history sidebar's conversations (see
app/db/models.py's `ChatSession` docstring). Separate from every existing table on purpose:
it stores the raw in-progress transcript (JSONB `state`), not approved DAG output, so a
strategist can reopen an unfinished chat exactly where they left it.

Hand-authored rather than autogenerated, matching every prior migration's approach (no live
Postgres instance available in this environment to autogenerate against) — verified by
compiling the equivalent `CREATE TABLE` DDL through the postgresql dialect against the
`ChatSession` model and cross-checking it matches what's written below.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1c4e6f2b7d3"
down_revision: Union[str, None] = "4dba3dae9f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "chat_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "title", sa.String(300), nullable=False, server_default=sa.text("'New chat'")
        ),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("run_id", name="uq_chat_sessions_run_id"),
    )
    op.create_index("ix_chat_sessions_updated_at", "chat_sessions", ["updated_at"])


def downgrade() -> None:
    op.drop_index("ix_chat_sessions_updated_at", table_name="chat_sessions")
    op.drop_table("chat_sessions")
